services:
  server:
    container_name: agents-freestylelibre
    image: libre-bot
    build:
      context: .
      target: prod
      network: "host"
      args:
        SOURCE_COMMIT: $SOURCE_COMMIT
    command: server
    restart: unless-stopped
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  worker:
    container_name: agents-freestylelibre-worker
    image: libre-bot
    build:
      context: .
      target: prod
      network: "host"
      args:
        SOURCE_COMMIT: $SOURCE_COMMIT
    command: fetch_task
    restart: unless-stopped
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
