services:
  agents-freestylelibre:
    image: docker.telepat.online/agents-freestylelibre-image:server-latest
    container_name: agents-freestylelibre-server
    env_file:
      - .env
      - enviroments/freestylelibre.env
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-freestylelibre
      - com.centurylinklabs.watchtower.enable=true

  agents-freestylelibre-worker:
    image: docker.telepat.online/agents-freestylelibre-image:worker-latest
    container_name: agents-freestylelibre-worker
    env_file:
      - .env
      - enviroments/freestylelibre.env
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db-init:
        condition: service_completed_successfully
      agents-freestylelibre:
        condition: service_started
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-freestylelibre
      - com.centurylinklabs.watchtower.enable=true
