services:
  server:
    container_name: agents-freestylelibre-server
    image: docker.telepat.online/agents-freestylelibre-image:latest
    restart: unless-stopped
    command: server
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false

  worker:
    container_name: agents-freestylelibre-worker
    image: docker.telepat.online/agents-freestylelibre-image:latest
    restart: unless-stopped
    command: fetch_task
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false
