services:
  server:
    container_name: freestylelibre-server-agent
    restart: always
    build:
      context: .
      target: prod
    command: server
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}

  worker:
    container_name: freestylelibre-worker-agent
    restart: always
    build:
      context: .
      target: prod
    command: fetch_task
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
