services:
  agents-freestylelibre:
    image: docker.telepat.online/agents-freestylelibre-image:latest
    container_name: agents-freestylelibre-server
    env_file:
      - .env
      - enviroments/freestylelibre.env
    environment:
      - SOURCE_COMMIT=${source_commit}
      - DEBUG=false
      - DB_PASSWORD=${postgres_password}
      - SERVER_HOST=""
      - SERVER_PORT=80
    command: server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-freestylelibre
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "80"

  agents-freestylelibre-worker:
    image: docker.telepat.online/agents-freestylelibre-image:latest
    container_name: agents-freestylelibre-worker
    env_file:
      - .env
      - enviroments/freestylelibre.env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_HOST=""
      - SERVER_PORT=80
    command: fetch_task
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-freestylelibre
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "80"
