https://api.libreview.ru

accept-encoding: gzip
cache-control: no-cache
connection: Keep-Alive
content-type: application/json; charset=utf-8
product: llu.android
version: 4.7
User-Agent: python-requests/2.31.0

--

--

POST /llu/auth/login

{
    "email": "***",
    "password": "***"
}


--

authorization: Bearer lol

GET /llu/connections


--

authorization: Bearer lol

GET /llu/connections/13458c36-c499-11ec-86e8-0242ac110006/graph
